# Generated by Django 5.1.4 on 2024-12-05 03:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_habitacion_estandar', models.IntegerField(default=10)),
                ('puntos_suite', models.IntegerField(default=15)),
                ('puntos_grupo', models.IntegerField(default=20)),
                ('puntos_estadia_corta', models.IntegerField(default=5)),
                ('puntos_estadia_media', models.IntegerField(default=10)),
                ('puntos_estadia_larga', models.IntegerField(default=20)),
                ('puntos_transporte', models.IntegerField(default=5)),
                ('puntos_tours', models.IntegerField(default=5)),
                ('puntos_spa', models.IntegerField(default=10)),
                ('multiplicador_temporada_alta', models.FloatField(default=1.5)),
                ('multiplicador_ultimo_minuto', models.FloatField(default=2.0)),
                ('bonus_fidelizacion', models.IntegerField(default=500)),
                ('huespedes_para_bonus', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Configuración de Puntos',
                'verbose_name_plural': 'Configuraciones de Puntos',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('puntos_base', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agencia', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('puntos_actuales', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_huesped', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('numero_habitaciones', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('numero_huespedes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('no_fumador', models.BooleanField(default=False)),
                ('vista_mar', models.BooleanField(default=False)),
                ('acceso_discapacitados', models.BooleanField(default=False)),
                ('cama_adicional', models.BooleanField(default=False)),
                ('transporte_aeropuerto', models.BooleanField(default=False)),
                ('tours_locales', models.BooleanField(default=False)),
                ('servicio_spa', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('comentarios', models.TextField(blank=True)),
                ('puntos_generados', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lidotel_app.agencia')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lidotel_app.tipohabitacion')),
            ],
        ),
    ]
