# Generated by Django 5.1.4 on 2024-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lidotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
